### ISSUE TITLE
`ModuleNotFoundError` when trying to download the Shakespeare data with the script you provided

### ISSUE THREAD

**Issue by KatlehoJordan** [Andrei-Aksionov/nanoGPTplus#9]
This repository seems promising, but I was running into an error very early in the walkthrough... I was hitting `ModuleNotFoundError` when trying to run the script to download the Shakespeare data. I tried also passing the `-m` flag, but still to no avail. Any tips?

**Comment by Andrei-Aksionov** [comment]
Hello @KatlehoJordan 

Thanks for spotting this issue. Honestly I didn't test loading of the dataset for quite a while :)
The issue was in the name of the download script: it was `download_tiny_shakespear.py` and in README file `download_tiny_shakespeare.py`. The difference is in the letter `e` in the end ( oops 😃 ).
I also noticed one more issue with type check guard and fixed it also. 

In a minute I'll merge changes to the main branch. Please test it.

**Comment by KatlehoJordan** [comment]
Thanks for responding.

This  did not solve the problem (I used tab-completion from terminal to direct to the path, rather than copying-and-pasting from the `README.md`).

When running the script as it's own entrypoint, it is not finding the `src` module that is referred to in the first line.

Here is a fork where I've added at the top of the `README.md` the exact steps I took and the error I encountered.

https://github.com/KatlehoJordan/nanoGPTplus?organization=KatlehoJordan&organization=KatlehoJordan

For completion, I've copied the relevant details here:

**Steps taken**

1. Fork the [repository](https://github.com/Andrei-Aksionov/nanoGPTplus)
2. Start up a GitHub Codespace in the browser.
3. Run `poetry install` from the terminal in the codespace.

```
@KatlehoJordan ➜ /workspaces/nanoGPTplus (main) $ poetry install
The currently activated Python version 3.10.4 is not supported by the project (~3.10.8).
Trying to find and use a compatible version. 

Poetry was unable to find a compatible version. If you have one, you can explicitly use it via the "env use" command.
```

4. Modify `pyproject.toml` to indicate 3.10.4
5. Run `poetry install` from the terminal again. This time the installations work, but a warning is given:

```
Warning: poetry.lock is not consistent with pyproject.toml. You may be getting improper dependencies. Run `poetry lock [--no-update]` to fix it.
```

6. Run `poetry lock` to update `poetry.lock`
7. Run `python src/data/scripts/download_tiny_shakespeare.py` from the terminal to download the data.

```
@KatlehoJordan ➜ /workspaces/nanoGPTplus (main) $ python src/data/scripts/download_tiny_shakespeare.py 
Traceback (most recent call last):
  File "/workspaces/nanoGPTplus/src/data/scripts/download_tiny_shakespeare.py", line 1, in <module>
    from src import config
ModuleNotFoundError: No module named 'src'
```

**Comment by Andrei-Aksionov** [comment]
Thanks for such a rich description of a problem.

I see what the problem is. 
When you do `poetry install` it install packages and also the project itself.
You can see it in the [`pyproject.toml`](https://github.com/Andrei-Aksionov/nanoGPTplus/blob/main/pyproject.toml#L6) file:
> [tool.poetry]
...
packages = [{include = "src"}]
version = "1.0.0"

After successful install the output should look like this:
>   • Installing tensorboard (2.12.0)
  • Installing torch (1.13.1)
  • Installing tqdm (4.64.1)
Installing the current project: nanogpt (1.0.0) 

Now I see that I forgot to rename `nanogpt` to `nanogptplus` 😄 

Anyway, back to your problem. It seems that something prevented from installing `src` package. I assume that this is because of the change of python version in `pyproject.toml` file. I assume that after you did `poetry.lock` you should have run `poetry install` one more time.

In a short that how it suppose to be done:
1. Change python version in pyproject.toml
2. poetry lock (or even better `poetry lock --no-update` since you only changed bugfix version of python)
3. poetry install

---

I could not replicate your issue on my machine. 
I've cloned my repo in a separate folder, installed python 3.10.4, activated it, tried to run poetry install, got the error, changed python version from 3.10.8 to 3.10.4, run poetry install and it worked without error (only mentioned that poetry.lock is not consistent with pyproject.toml).

I tried to do the same in github codespaces (though I've never used it before, so I might did something not correctly).
1. I've created blank codespace
2. cloned my repo
3. changed directory: cd nanoGPTplus
4. created virtual environment: python -m venv venv
5. activated it: source venv/bin/activate
6. as there is no poetry on the codespaces machine, I installed it in the venv: pip install poetry
and the rest is the same: poetry install, got error, changed python version in pyproject.toml file, poetry install, after that all three scripts (download data, train and generate) worked without problems.

---

Anyway, I am planning to change required python version since there is so much hustle to change it manually. I am thinking to downgrade it to python3.8 (in order to work on Google Colab). Some changes in the code are required since I used some new functionality that was introduced in python3.10.

**Comment by KatlehoJordan** [comment]
I will try to revisit this in the next 48 hours to see if I get it working with your feedback.

Thank you!

**Comment by KatlehoJordan** [comment]
> 1. I've created blank codespace
> 2. cloned my repo
> 3. changed directory: cd nanoGPTplus
> 4. created virtual environment: python -m venv venv
> 5. activated it: source venv/bin/activate
> 6. as there is no poetry on the codespaces machine, I installed it in the venv: pip install poetry
>    and the rest is the same: poetry install, got error, changed python version in pyproject.toml file, poetry install, after that all three scripts (download data, train and generate) worked without problems.

Here we did things in a slightly different order; I forked the repository first, then from the repository created a codespace on the `main` branch. The default codespace configuration was smart enough to detect that `poetry` would be needed and installed it for me once the codespace was launched.

In any case, with your instructions, I was able to get the script to work, 😄 .

After starting the codespace, I followed your tips up to the `poetry install` step. Thereafter I did `poetry shell`, then `python src/data/scripts/download_tiny_shakespeare.py`... Success! 🥳 

Thank you for your work and your help!

**Comment by Andrei-Aksionov** [comment]
Glad that it worked for you. 

That reminded me that I wanted to add at least smoke tests, but never did.
Now the repo includes simple smoke tests for dataset download, train for bigram and gpt models and new tokens generation. Plus I added a github workflow for each pull requests, so it will run these smoke tests on linux/macos with python 3.8/3.9/3.10. Seems like for python3.11 pytorch is available only on linux platform. And as for windows ... I didn't manage to make it work with github actions and I don't have windows locally, so I guess I have to assume that everything is fine 😸
